/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.paradigmatecnologico.binaryrpc.avro.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum State { 
  MARRIED, SINGLE, UNDEFINED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"State\",\"namespace\":\"com.paradigmatecnologico.binaryrpc.avro.model\",\"symbols\":[\"MARRIED\",\"SINGLE\",\"UNDEFINED\"],\"default\":\"UNDEFINED\"}");
}
