/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.paradigmatecnologico.binaryrpc.avro.service;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AvroTestService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroTestService\",\"namespace\":\"com.paradigmatecnologico.binaryrpc.avro.service\",\"types\":[{\"type\":\"record\",\"name\":\"RequestData\",\"fields\":[{\"name\":\"ID\",\"type\":\"double\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"state\",\"type\":{\"type\":\"enum\",\"name\":\"State\",\"symbols\":[\"MARRIED\",\"SINGLE\",\"UNDEFINED\"],\"default\":\"UNDEFINED\"}},{\"name\":\"telephones\",\"type\":{\"type\":\"map\",\"values\":\"long\"}},{\"name\":\"addresses\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"member\",\"type\":[\"boolean\",\"null\"]},{\"name\":\"description\",\"type\":[\"string\",\"null\"]}]},{\"type\":\"record\",\"name\":\"Search\",\"fields\":[{\"name\":\"field\",\"type\":[\"string\",\"null\"]},{\"name\":\"value\",\"type\":[\"string\",\"null\"]}]},{\"type\":\"record\",\"name\":\"Response\",\"fields\":[{\"name\":\"code\",\"type\":[\"int\",\"null\"]},{\"name\":\"message\",\"type\":[\"string\",\"null\"]},{\"name\":\"responseData\",\"type\":[\"RequestData\",\"null\"]}]}],\"messages\":{\"create\":{\"request\":[{\"name\":\"request\",\"type\":\"RequestData\"}],\"response\":\"Response\"},\"search\":{\"request\":[{\"name\":\"request\",\"type\":\"Search\"}],\"response\":\"Response\"}}}");
  com.paradigmatecnologico.binaryrpc.avro.service.Response create(com.paradigmatecnologico.binaryrpc.avro.service.RequestData request) throws org.apache.avro.AvroRemoteException;
  com.paradigmatecnologico.binaryrpc.avro.service.Response search(com.paradigmatecnologico.binaryrpc.avro.service.Search request) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends AvroTestService {
    public static final org.apache.avro.Protocol PROTOCOL = com.paradigmatecnologico.binaryrpc.avro.service.AvroTestService.PROTOCOL;
    void create(com.paradigmatecnologico.binaryrpc.avro.service.RequestData request, org.apache.avro.ipc.Callback<com.paradigmatecnologico.binaryrpc.avro.service.Response> callback) throws java.io.IOException;
    void search(com.paradigmatecnologico.binaryrpc.avro.service.Search request, org.apache.avro.ipc.Callback<com.paradigmatecnologico.binaryrpc.avro.service.Response> callback) throws java.io.IOException;
  }
}