/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.paradigmatecnologico.binaryrpc.avro.service;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Response extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Response\",\"namespace\":\"com.paradigmatecnologico.binaryrpc.avro.service\",\"fields\":[{\"name\":\"code\",\"type\":[\"int\",\"null\"]},{\"name\":\"message\",\"type\":[\"string\",\"null\"]},{\"name\":\"responseData\",\"type\":[{\"type\":\"record\",\"name\":\"RequestData\",\"fields\":[{\"name\":\"ID\",\"type\":\"double\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"state\",\"type\":{\"type\":\"enum\",\"name\":\"State\",\"symbols\":[\"MARRIED\",\"SINGLE\",\"UNDEFINED\"],\"default\":\"UNDEFINED\"}},{\"name\":\"telephones\",\"type\":{\"type\":\"map\",\"values\":\"long\"}},{\"name\":\"addresses\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"member\",\"type\":[\"boolean\",\"null\"]},{\"name\":\"description\",\"type\":[\"string\",\"null\"]}]},\"null\"]}]}");
  @Deprecated public java.lang.Integer code;
  @Deprecated public java.lang.CharSequence message;
  @Deprecated public com.paradigmatecnologico.binaryrpc.avro.service.RequestData responseData;

  /**
   * Default constructor.
   */
  public Response() {}

  /**
   * All-args constructor.
   */
  public Response(java.lang.Integer code, java.lang.CharSequence message, com.paradigmatecnologico.binaryrpc.avro.service.RequestData responseData) {
    this.code = code;
    this.message = message;
    this.responseData = responseData;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return code;
    case 1: return message;
    case 2: return responseData;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: code = (java.lang.Integer)value$; break;
    case 1: message = (java.lang.CharSequence)value$; break;
    case 2: responseData = (com.paradigmatecnologico.binaryrpc.avro.service.RequestData)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'code' field.
   */
  public java.lang.Integer getCode() {
    return code;
  }

  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.Integer value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }

  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'responseData' field.
   */
  public com.paradigmatecnologico.binaryrpc.avro.service.RequestData getResponseData() {
    return responseData;
  }

  /**
   * Sets the value of the 'responseData' field.
   * @param value the value to set.
   */
  public void setResponseData(com.paradigmatecnologico.binaryrpc.avro.service.RequestData value) {
    this.responseData = value;
  }

  /** Creates a new Response RecordBuilder */
  public static com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder newBuilder() {
    return new com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder();
  }
  
  /** Creates a new Response RecordBuilder by copying an existing Builder */
  public static com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder newBuilder(com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder other) {
    return new com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder(other);
  }
  
  /** Creates a new Response RecordBuilder by copying an existing Response instance */
  public static com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder newBuilder(com.paradigmatecnologico.binaryrpc.avro.service.Response other) {
    return new com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder(other);
  }
  
  /**
   * RecordBuilder for Response instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Response>
    implements org.apache.avro.data.RecordBuilder<Response> {

    private java.lang.Integer code;
    private java.lang.CharSequence message;
    private com.paradigmatecnologico.binaryrpc.avro.service.RequestData responseData;

    /** Creates a new Builder */
    private Builder() {
      super(com.paradigmatecnologico.binaryrpc.avro.service.Response.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Response instance */
    private Builder(com.paradigmatecnologico.binaryrpc.avro.service.Response other) {
            super(com.paradigmatecnologico.binaryrpc.avro.service.Response.SCHEMA$);
      if (isValidValue(fields()[0], other.code)) {
        this.code = data().deepCopy(fields()[0].schema(), other.code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message)) {
        this.message = data().deepCopy(fields()[1].schema(), other.message);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.responseData)) {
        this.responseData = data().deepCopy(fields()[2].schema(), other.responseData);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'code' field */
    public java.lang.Integer getCode() {
      return code;
    }
    
    /** Sets the value of the 'code' field */
    public com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder setCode(java.lang.Integer value) {
      validate(fields()[0], value);
      this.code = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'code' field has been set */
    public boolean hasCode() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'code' field */
    public com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder clearCode() {
      code = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'message' field */
    public java.lang.CharSequence getMessage() {
      return message;
    }
    
    /** Sets the value of the 'message' field */
    public com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.message = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'message' field has been set */
    public boolean hasMessage() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'message' field */
    public com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder clearMessage() {
      message = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'responseData' field */
    public com.paradigmatecnologico.binaryrpc.avro.service.RequestData getResponseData() {
      return responseData;
    }
    
    /** Sets the value of the 'responseData' field */
    public com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder setResponseData(com.paradigmatecnologico.binaryrpc.avro.service.RequestData value) {
      validate(fields()[2], value);
      this.responseData = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'responseData' field has been set */
    public boolean hasResponseData() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'responseData' field */
    public com.paradigmatecnologico.binaryrpc.avro.service.Response.Builder clearResponseData() {
      responseData = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Response build() {
      try {
        Response record = new Response();
        record.code = fieldSetFlags()[0] ? this.code : (java.lang.Integer) defaultValue(fields()[0]);
        record.message = fieldSetFlags()[1] ? this.message : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.responseData = fieldSetFlags()[2] ? this.responseData : (com.paradigmatecnologico.binaryrpc.avro.service.RequestData) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
